### ISSUE TITLE
uxlink 

### ISSUE THREAD

**Issue by xzhengyu3** [Fooyao/web3Task#1]
请问帅哥，
请问这个 https://api.uxlink.io/activity/uxcheckin/third/wallet  接口 有文档么，现在入参校验不过

**Comment by Fooyao** [comment]
> 请问帅哥， 请问这个 https://api.uxlink.io/activity/uxcheckin/third/wallet 接口 有文档么，现在入参校验不过

这个应该是网站问题，我昨晚测试还是正常的
