### ISSUE TITLE
我手动点官网授权是正常的，但是脚本跑起来好像不行

### ISSUE THREAD

**Issue by Nasak2** [Fooyao/web3Task#4]
![2222](https://github.com/user-attachments/assets/1e99869f-4245-4c49-bfda-a638e9fa141d)
![微信截图_20240828144503](https://github.com/user-attachments/assets/b131b436-2759-4e3d-960c-6cf46bdd8150)

**Comment by Nasak2** [comment]
使用的是你刚更新的那个保存成功token的

**Comment by Gen9yanx1n** [comment]
有解决方法了嘛

**Comment by dzzzzzzzzzzy** [comment]
解决了吗

**Comment by scan1212** [comment]
怎么解决啊
