### ISSUE TITLE
400 500

### ISSUE THREAD

**Issue by QTyang** [Fooyao/web3Task#5]
今天全是这种情况，最新代码也是，有没有兄弟解决的
![1724914333045](https://github.com/user-attachments/assets/e1dbf349-9823-4e37-b86f-ec44100f7ac9)

**Comment by Fooyao** [comment]
手动也这样啊，脚本能咋更新？

**Comment by QTyang** [comment]
> 手动也这样啊，脚本能咋更新？

好的，不是我的问题就行。

**Comment by qq782008524** [comment]
现在可以了吗

**Comment by xianquan3230** [comment]
你好请问你遇到了 关注推特链接超时的问题吗？怎么解决的啊
