### ISSUE TITLE
获取谷歌验证码失败 有人知道怎么搞吗

### ISSUE THREAD

**Issue by skierlin** [Fooyao/web3Task#6]
![image](https://github.com/user-attachments/assets/20140738-c2ad-43b6-a3b2-f759e2086323)

**Comment by QTyang** [comment]
获取ApiKey那两个网址里得有余额才能用

**Comment by skierlin** [comment]
充值了呀，买帐号了，现在是获取失败，不是破解失败

**Comment by Fooyao** [comment]
你ApiKey填错了吧估计

**Comment by skierlin** [comment]
不好意思，买完套餐居然又有一个key，用那个key过去这一步了，现在卡在下一步了

![Uploading image.png…]()

**Comment by skierlin** [comment]
![image](https://github.com/user-attachments/assets/b4761543-2d1a-4da9-88e1-edba643f47c1)
