### ISSUE TITLE
老哥，nstproxy这家的代理我一直没测通耶，对网络环境有啥要求的嘛，我换另外一家的也没跑通。

### ISSUE THREAD

**Issue by siran575** [Fooyao/web3Task#7]
![image](https://github.com/user-attachments/assets/7ba3ba07-0771-4031-ace8-e304922c8fba)

**Comment by Hyin78** [comment]
啥你能跑通？
不可能啊

**Comment by nontimebomala** [comment]
电脑已经做了代理的话，跑代码带noproxy版本可以吗？

**Comment by childsnail** [comment]
遇到和楼主一样的问题了，楼主解决了吗？
